### ISSUE TITLE
The access token is wrong.

### ISSUE THREAD

**Issue by bnubobby** [xxl-job/xxl-job-executor-go#1]
目前最新版使用的token header 为   XXL-JOB-ACCESS-TOKEN
但在本项目中，使用的是：
request.Header.Set("XXL-RPC-ACCESS-TOKEN", e.opts.AccessToken)

**Comment by feixiaobo** [comment]
> 目前最新版使用的token header 为 XXL-JOB-ACCESS-TOKEN
> 但在本项目中，使用的是：
> request.Header.Set("XXL-RPC-ACCESS-TOKEN", e.opts.AccessToken)

我更新的最新版本已兼容v2.2.0 ,有需要参考 https://github.com/feixiaobo/go-xxl-job-client

**Comment by guoruibiao** [comment]
```bash
➜  example go run main.go 
Starting server at 127.0.0.1:9999
2020/11/23 16:34:49 执行器注册失败1:Post "http://127.0.0.1/xxl-job-admin/api/registry": dial tcp 127.0.0.1:80: connect: connection refused
2020/11/23 16:35:01 执行器摘除失败:Post "http://127.0.0.1/xxl-job-admin/api/registryRemove": dial tcp 127.0.0.1:80: connect: connection refused
... ...
```

**Comment by rushuinet** [comment]
你本地有启动 xxl-job-admin 吗？或者查看一下启动端口是否正确

**Comment by rushuinet** [comment]
> 目前最新版使用的令牌头为XXL-JOB-ACCESS-TOKEN
> 但在本项目中，使用的是：
> request.Header.Set（“ XXL-RPC-ACCESS-TOKEN”，e.opts.AccessToken）

已处理
