### ISSUE TITLE
请问大佬这个是基于xxl-job什么版本开发的？

### ISSUE THREAD

**Issue by Lexus90** [xxl-job/xxl-job-executor-go#11]
v2.2.0和之前的版本差异较大，作者具体是基于哪个版本开发的GO SDK的呀？

**Comment by yoyofx** [comment]
我这没用 2.3.0 没有任何问题， 应该2.2.0 之后的版本都可以的

**Comment by rushuinet** [comment]
v2.2.0

**Comment by rushuinet** [comment]
我测试下来xxl-job-admin:2.3.0 没问题;
现在新版本支持了路由策略里故障转移，忙时转移，之前版本有点问题
