### ISSUE TITLE
xxl-job 2.3.0 使用异常

### ISSUE THREAD

**Issue by tianbocheng** [xxl-job/xxl-job-executor-go#13]
服务端接收参数：
![image](https://user-images.githubusercontent.com/20829408/119594427-57fdc300-be0e-11eb-8e9f-d4d3afdcf1b0.png)

客户端发送参数：
![image](https://user-images.githubusercontent.com/20829408/119594508-7fed2680-be0e-11eb-877c-afccfc2b610b.png)

结果：
xxl-job-admin 界面端无法查看到执行结果
![image](https://user-images.githubusercontent.com/20829408/119594761-fa1dab00-be0e-11eb-9ab4-44afa9eb6975.png)

建议：
![image](https://user-images.githubusercontent.com/20829408/119594614-b32fb580-be0e-11eb-8227-1e03b3af334e.png)

**Comment by rushuinet** [comment]
目前该项目是基于v2.2.0开发的，近期会根据最新版本调试一下，具体时间以项目更新为准

**Comment by rushuinet** [comment]
这位同学，仔细看了一下你的问题，taskFunc(...) string 任务返回的这个string就是执行备注，你可以返回个试下，，v2.3.0下测试正常

**Comment by rushuinet** [comment]
v1.0.0已解决
