### ISSUE TITLE
大神，请问怎么打印日志到xxl-admin的日志中

### ISSUE THREAD

**Issue by tuppercnit** [xxl-job/xxl-job-executor-go#14]
你的例子中没有只有fmt打印，有没有例子可以直接打印到xxl-admin上的日志？

**Comment by dgqypl** [comment]
看了一下源码，以当前版本的xxl-job-executor-go来讲，不能打印到xxl-admin上。
对比了一下java版本的executor，java是通过每次执行task，将日志输出到executor中一个固定的目录下的文件中，当你在admin界面中点击查看执行日志时，admin会向executor发送请求获取文件中的日志内容。这部分逻辑在现有版本的xxl-job-executor-go中没有。

**Comment by rushuinet** [comment]
现在大多使用容器部署，日志会统一输出到日志系统，xxl-job-executor-go 留有日志接口，对接到自己的日志系统即可。
