### ISSUE TITLE
v0.6.1 报panic 错误

### ISSUE THREAD

**Issue by jiayiming001** [xxl-job/xxl-job-executor-go#19]
2021/08/20 06:49:30 callback err : %!(EXTRA string=Post http://xxl-job/xxl-job-admin/api/callback: EOF)
goroutine 467204 [running]:
runtime/debug.Stack(0x1, 0x1, 0x83)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/xxl-job/xxl-job-executor-go.(*Task).Run.func1(0xc00058f800, 0xc00046d4e0, 0xc0003cc1c0)
	/go/pkg/mod/github.com/xxl-job/xxl-job-executor-go@v0.6.1/task.go:31 +0x20f
panic(0xecec80, 0x1978140)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/xxl-job/xxl-job-executor-go.(*executor).callback(0xc0002552b0, 0xc00058f800, 0xc8, 0x0, 0x0)
	/go/pkg/mod/github.com/xxl-job/xxl-job-executor-go@v0.6.1/executor.go:312 +0xda
github.com/xxl-job/xxl-job-executor-go.(*executor).runTask.func1(0xc8, 0x0, 0x0)
	/go/pkg/mod/github.com/xxl-job/xxl-job-executor-go@v0.6.1/executor.go:166 +0x51
github.com/xxl-job/xxl-job-executor-go.(*Task).Run(0xc00058f800, 0xc00046d4e0)
	/go/pkg/mod/github.com/xxl-job/xxl-job-executor-go@v0.6.1/task.go:37 +0xbe
created by github.com/xxl-job/xxl-job-executor-go.(*executor).runTask
	/go/pkg/mod/github.com/xxl-job/xxl-job-executor-go@v0.6.1/executor.go:165 +0x699

**Comment by jiayiming001** [comment]
![image](https://user-images.githubusercontent.com/32919372/130387129-c69b35fe-16c1-4003-8b97-012d9d2233dc.png)

**Comment by jiayiming001** [comment]
![image](https://user-images.githubusercontent.com/32919372/130387191-322555b3-b709-43f2-a137-63bbd74f7fbb.png)

**Comment by jiayiming001** [comment]
不过在最外层有recovery 不会导致 进程挂掉， 目前v1.0.0 也有这个写法

**Comment by rushuinet** [comment]
感谢反馈，最新版本已修复
