### ISSUE TITLE
Executor 部署在Docker中时可能不能正常工作

### ISSUE THREAD

**Issue by bluceyee** [xxl-job/xxl-job-executor-go#29]
问题： 当Executor 使用docker部署的时候， Executor的访问需要通过宿主机进行映射，当前配置中ExecutorIP:ExecutorPort 同时用于run服务以及向xxl-job-admin注册，会导致可以注册成功，但是任务回调会失败。
如如下错误：
![image](https://user-images.githubusercontent.com/18377280/156286065-ff735b31-e540-4e8b-9c17-ade2c53b633b.png)

解决办法：将run服务以及注册任务回调的ip:port 区分配置。

**Comment by rushuinet** [comment]
要保障调度器到podIP访问可达，这个是网络问题

**Comment by zoulux** [comment]
主要原因是 executor 既作为客户端又需要作为服务端

**Comment by rushuinet** [comment]
可以参考这个，把xxl-job-executor当作路由用，用自己定义的服务来执行：https://github.com/gin-middleware/xxl-job-executor/blob/main/middleware.go
