### ISSUE TITLE
使用示例后，登录admin，发现在执行器管理列表查不到

### ISSUE THREAD

**Issue by wsq2025** [xxl-job/xxl-job-executor-go#42]
该工具的执行器只是在xxl-job-admin的xxl_job_registry表中增加了一条记录，而执行器管理列表查询的是xxl_job_group表的数据。感觉工具志做了一半的事情

**Comment by rushuinet** [comment]
执行器实现了调度器的接口，要先在admin里添加执行器才可以

**Comment by today2014** [comment]
不能自动 添加执行器么？
