### ISSUE TITLE
Executor注册时不能使用公网IP

### ISSUE THREAD

**Issue by qfzc** [xxl-job/xxl-job-executor-go#50]
大佬，Executor 端部署时注册IP只能填写本机内网IP，如果填入公网IP无法被admin调用，端口也没有起来。     admin 和 executor 不在一台服务器上。也不在同一个内网网段

**Comment by qfzc** [comment]
Executor 注册时使用内网IP， 注册成功，去Admin端把Executor IP手动改成公网IP，这个是可以成功调用任务的

**Comment by rushuinet** [comment]
使用最新版本[v1.1.2](https://github.com/xxl-job/xxl-job-executor-go/releases/tag/v1.1.2)解决了该问题
