### ISSUE TITLE
如何返回日志LogHandler

### ISSUE THREAD

**Issue by dxl3811051** [xxl-job/xxl-job-executor-go#60]
![image](https://user-images.githubusercontent.com/34296773/220567070-c4aa9a31-f203-4c6e-a887-fdd7368c44ca.png)
这个是样例的，http://127.0.0.1:8080/xxl-job-admin/joblog/logDetailPage?id=156  去查询的话永远是
![image](https://user-images.githubusercontent.com/34296773/220567547-43862039-4286-4231-a4cd-e91bc4f75f91.png)
哪位大佬能给个样例 写个func能让我随时 在代码中 返回日志到调度中心

**Comment by rushuinet** [comment]
你把LogContent字段的内容换成你日志的内容就OK啦

**Comment by dxl3811051** [comment]
> 你把LogContent字段的内容换成你日志的内容就OK啦

大佬 我是菜鸡 能给个例子如何在别的地方调用？比如我想在任务脚本里面返回给调度中心日志 这个函数怎么写？
 感激不尽。。。
![image](https://user-images.githubusercontent.com/34296773/220804870-a96581d7-8000-43a9-93c3-fb4641416ad2.png)

**Comment by dxl3811051** [comment]
你好啊 ，我想问问 能给个例子么 ？比如我想在任务脚本里面返回给调度中心日志 这个函数怎么写？ 我比较菜 不知道如何写了？




&nbsp;


杜鑫龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xxl-job/xxl-job-executor-go] 如何返回日志LogHandler (Issue #60)





 
你把LogContent字段的内容换成你日志的内容就OK啦

**Comment by dxl3811051** [comment]
> 你把LogContent字段的内容换成你日志的内容就OK啦

我有点明白你的意思了  ，但是这个日志只能一下一下发起请求从日志文件取出么  不能类似原生那样不用多次请求就刷新日志？

**Comment by rushuinet** [comment]
你看下日志参数里有分页参数，你实现日志分页功能即可，这个接口就是用的原生的
