### ISSUE TITLE
请问下能否给task加上类似grpc的拦截器，可以自定义的去写一些中间件（trace、metric等等）

### ISSUE THREAD

**Issue by wsx864321** [xxl-job/xxl-job-executor-go#62]
如果有需要我可以提一个pr

**Comment by s5364733** [comment]
> 如果有需要我可以提一个pr
Recently, we are preparing the fork library for secondary development, and your issue is in our plan

**Comment by s5364733** [comment]
> 如果有需要我可以提一个pr

Recently, we are preparing the fork library for secondary development, and your issue is in our plan

**Comment by wsx864321** [comment]
> 

its good

**Comment by wsx864321** [comment]
> > 如果有需要我可以提一个pr
> 
> Recently, we are preparing the fork library for secondary development, and your issue is in our plan
its good

**Comment by wsx864321** [comment]
> > 如果有需要我可以提一个pr
> 
> Recently, we are preparing the fork library for secondary development, and your issue is in our plan

its good

**Comment by rushuinet** [comment]
新版本已经支持中间件
