### ISSUE TITLE
使用xxljob 代码逻辑自定义任务最终的失败和成功状态

### ISSUE THREAD

**Issue by org-lib** [xxl-job/xxl-job-executor-go#67]
代码逻辑无法正常执行的时候，返回的只是string 错误信息，但是任务最终状态还是完成。这个不合理的，如何代码控制让xxljob返回失败的状态，不能panic 因为别的定时任务要执行，

**Comment by rushuinet** [comment]
任务的panic只会影响当前使用，不会影响别的定时任务的
